### ISSUE TITLE
ID 10 | Caso de Uso "Emitir Relatórios" não existe no formulário de casos de uso.

### ISSUE THREAD

**Issue by guilhermevieirasilvagoncalves** [guilhermevieirasilvagoncalves/Sistema-de-Judocas#13]
Caso de uso "Emitir Relatórios" não existe no formulário de casos de uso.

Descrição: Na especificação de requisitos consta o caso, entretanto, ele não está no diagrama de casos de uso do documento.

Severidade: Alta

Linha/Seção: Não se aplica

**Comment by amandapollosarlo** [comment]
Corrigido no commit 834854a.
