### ISSUE TITLE
ID 7 | O caso de uso "Apagar Entidade" não está detalhado no formulário de casos de uso.

### ISSUE THREAD

**Issue by marappoli** [guilhermevieirasilvagoncalves/Sistema-de-Judocas#8]
Caso de uso "Apagar Entidade" não existe nos Formulários de Caso de Uso.

Descrição: Na especificação de requisitos consta o caso, entretanto, ele não está implementado no Formulário de Casos de Uso.

Severidade: Alta

Linha/Seção: Não se aplica

**Comment by amandapollosarlo** [comment]
Corrigido no commit 834854a.
