### ISSUE TITLE
ID 4 | Caso de Uso "Relatório de aniversariantes do mês" não existe na especificação.

### ISSUE THREAD

**Issue by guilhermevieirasilvagoncalves** [guilhermevieirasilvagoncalves/Sistema-de-Judocas#9]
Caso de uso "Relatório de aniversariantes do mês" não existe na especificação do projeto.

Descrição: Na especificação de requisitos consta o caso, entretanto, ele não está no diagrama de casos de uso e na especificação de casos de uso do documento.

Severidade: Alta

Linha/Seção: Não se aplica

**Comment by amandapollosarlo** [comment]
Corrigido no commit 7e7937b.
